# configuration.yaml USB-Gateway(default) & LAN-Gateway
# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join. !! Set to false after pairung all your devices !!
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL - IP-adress:Port
  server: mqtt://172.17.31.113:1883
  # MQTT server authentication (user & pasword), uncomment if required:
  user: 
  password: 

# Serial settings
serial:
  # Location USB Gateway (default) - comment out if using LAN-Gateway
  port: /dev/ttyACM0 
  # Location LAN-Gateway (IP-adress:Socket Port) - comment out if using USB-Gateway
  # port: tcp://172.17.31.68:6638
advanced:
  network_key: GENERATE
frontend:
  port: 8080
