# Inhalt configuration.yaml (USB-Gateway)
# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: mqtt://172.17.31.113:1883
  # MQTT server authentication, uncomment if required:
  user: 
  password: 

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyACM0  
advanced:
  network_key: GENERATE
frontend:
  port: 8080
